spring:
  application:
    name: book-management-server

  cache:
    type: redis

  redis:
    host: 127.0.0.1  # Reids 服务器地址
    port: 6379  # Redis 服务器端口
    password:
    timeout: 10000 #读超时时间
    connect-timeout: 60000 # 写超时时间
    lettuce:
      pool:
        enabled: true # 开启连接池
        max-idle: 8 # 最大空闲连接数
        max-wait: 1ms
        max-active: 8
        min-idle: 0
        time-between-eviction-runs: 600000

  datasource:
    url: jdbc:mysql://localhost:3306/online_library?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null

mybatis:
  type-aliases-package: com.itheima.book.model
  mapper-locations: classpath:com/itheima/book/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名 Java类中属性和 和表中字段自动映射，比如, userId <->user_id
    cache-enabled: false #使全局的映射器启用或禁用缓存。
    lazy-loading-enabled: false #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载。
    aggressive-lazy-loading: true #当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载。
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启日志，方便查看sql
# pagehelper配置
pagehelper:
  helper-dialect: mysql #指定分页数据库类型（方言）
  reasonable: true #合理查询超过最大页，则查询最后一页
  support-methods-arguments: true # 支持通过Mapper接口参数来传递分页参数，默认false
  params: pacount=countSql # POJO或者Map中发现了countSql属性，就会作为count参数使用

server:
  port: 8081

logging:
  level:
    root: INFO
    com.example.bookmanagementserver: DEBUG
book:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication
